name: HSMOA → Slack (09:00 KST)

on:
  schedule:
    # 09:00 KST == 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install playwright requests
      - run: python -m playwright install --with-deps chromium
      - name: Post filtered HSMOA schedule
        run: python hsmoa_to_slack.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          # 텍스트 클릭은 안 쓰면 비워둬도 됨
          HSMOA_SHOP: ${{ secrets.HSMOA_SHOP }}
          HSMOA_CATEGORY: ${{ secrets.HSMOA_CATEGORY }}
          # ✅ 로고/아이콘 기반 필터만 사용
          HSMOA_SHOP_LOGO: ${{ secrets.HSMOA_SHOP_LOGO }}
          HSMOA_CATEGORY_LOGO: ${{ secrets.HSMOA_CATEGORY_LOGO }}
